name: "docker-build"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write 
      packages: write 
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: 'jbowen93/debug-gh-action'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: update go.mod
        run: |
          echo $PWD
          go mod edit -replace=github.com/tharsis/ethermint=github.com/jbowen93/ethermint@jbowen93-optimint
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/jbowen93/evmos:gh-action
          file: docker/Dockerfile

# go mod edit -replace=github.com/celestiaorg/optimint=github.com/celestiaorg/optimint@939aa77

# docker-build-debug:
#     runs-on: "ubuntu-latest"
#     permissions:
#       contents: write 
#       packages: write 
#     steps:
#       - name: "Checkout source code"
#         uses: "actions/checkout@v2"
#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.17
#       # - name: Checkout Optimint
#       #   uses: actions/checkout@v2
#       #   with:
#       #     repository: celestiaorg/optimint
#       #     path: optimint
#       #     ref: 939aa77 
#       # - name: tidy optimint
#       #   run: |
#       #     cd optimint
#       #     rm -rf .git
#       #     go mod tidy -compat=1.17 -e
#       # - name: Checkout Ethermint
#       #   uses: actions/checkout@v2
#       #   with:
#       #     repository: jbowen93/ethermint
#       #     path: ethermint
#       #     ref: jbowen93-optimint
#       - name: tidy ethermint
#         run: |
#           cd ethermint
#           rm -rf .git
#           go mod tidy -compat=1.17 -e
#       - name: update go.mod
#         run: |
#           echo $PWD
#           go mod edit -replace=github.com/celestiaorg/optimint=github.com/celestiaorg/optimint@939aa77
#           go mod edit -replace=github.com/tharsis/ethermint=github.com/jbowen93/ethermint@jbowen93-optimint
#       # - name: almost-build
#       #   run: ./almost-build.sh
#       # - name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v1
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to GHCR
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: ghcr.io/jbowen93/evmos:gh-action
#           file: docker/Dockerfile
