name: "docker-build"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write 
      packages: write 
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: 'jbowen93/debug-gh-action'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: false
          tags: ghcr.io/jbowen93/evmos:gh-action
          file: docker/Dockerfile